name: Lint Docs

on:
  push:
    branches:
    - master
    paths:
    - "**/*.md"
    - ".github/workflows/docs-lint.yml"
  pull_request:
    paths:
    - "**/*.md"
    - ".github/workflows/docs-lint.yml"

jobs:
  docs-lint:
    uses: anycable/github-actions/.github/workflows/docs-lint.yml@master
    with:
      mdl-path: "*.md"
      rubocop: false
      forspell-args: "*.md"
      lychee-args: docs/* --exclude "(recipes|profilers|misc)/"
