name: Lint Docs

on:
  push:
    branches:
    - master
    paths:
    - ".github/**/*.yml"
    - "**/*.md"
    - "**/*.html"
  pull_request:
    paths:
    - ".github/**/*.yml"
    - "**/*.md"
    - "**/*.html"

jobs:
  markdownlint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
    - name: Run Markdown linter
      run: |
        gem install mdl
        mdl docs

  rubocop:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
    - name: Lint Markdown files with RuboCop
      run: |
        gem install bundler
        bundle install --gemfile gemfiles/rubocop.gemfile --jobs 4 --retry 3
        bundle exec --gemfile gemfiles/rubocop.gemfile rubocop

  forspell:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Hunspell
      run: |
        sudo apt-get install hunspell
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
    - name: Cache installed gems
      uses: actions/cache@v1
      with:
        path: /home/runner/.rubies/ruby-2.7.0/lib/ruby/gems/2.7.0
        key: gems-cache-${{ runner.os }}
    - name: Install Forspell
      run: gem install forspell
    - name: Run Forspell
      run: forspell docs/

  liche:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.13.x
    - name: Install liche
      run: |
        export PATH=$PATH:$(go env GOPATH)/bin
        go get -u github.com/raviqqe/liche
    - name: Run liche
      run: |
        export PATH=$PATH:$(go env GOPATH)/bin
        liche -c 2 -r docs/* -d docs/ -x "(recipes|profilers|misc)/"
